function build_longitudinal_vehicle_starter()
% Build the MEKAI longitudinal vehicle starter model.

setup_longitudinal_vehicle_starter();

model = "mekai_longitudinal_vehicle_starter";
modelFile = model + ".slx";

if bdIsLoaded(model)
    close_system(model, 0);
end

if isfile(modelFile)
    delete(modelFile);
end

new_system(model);
load_system("simulink");

set_param(model, ...
    "StopTime", "simConfig.stopTime", ...
    "Solver", "ode45", ...
    "SaveFormat", "StructureWithTime", ...
    "ReturnWorkspaceOutputs", "on");

add_block("simulink/Sources/From Workspace", model + "/Target Speed", ...
    "VariableName", "targetSpeedProfile", ...
    "Position", [60 90 180 120]);

add_block("simulink/Sources/From Workspace", model + "/Road Grade", ...
    "VariableName", "roadGradeProfile", ...
    "Position", [60 220 180 250]);

add_block("simulink/Ports & Subsystems/Subsystem", model + "/Driver Controller", ...
    "Position", [260 50 520 190]);
add_block("simulink/Ports & Subsystems/Subsystem", model + "/Vehicle Plant", ...
    "Position", [610 50 930 260]);

buildDriverController(model + "/Driver Controller");
buildVehiclePlant(model + "/Vehicle Plant");

add_block("simulink/Sinks/To Workspace", model + "/Vehicle Speed Out", ...
    "VariableName", "vehicleSpeed_mps", ...
    "SaveFormat", "Array", ...
    "Position", [980 80 1090 110]);
add_block("simulink/Sinks/To Workspace", model + "/Vehicle Accel Out", ...
    "VariableName", "vehicleAccel_mps2", ...
    "SaveFormat", "Array", ...
    "Position", [980 125 1090 155]);
add_block("simulink/Sinks/To Workspace", model + "/Distance Out", ...
    "VariableName", "vehicleDistance_m", ...
    "SaveFormat", "Array", ...
    "Position", [980 170 1090 200]);
add_block("simulink/Sinks/To Workspace", model + "/Net Force Out", ...
    "VariableName", "netForce_N", ...
    "SaveFormat", "Array", ...
    "Position", [980 215 1090 245]);
add_block("simulink/Sinks/To Workspace", model + "/Throttle Out", ...
    "VariableName", "throttleCmd", ...
    "SaveFormat", "Array", ...
    "Position", [560 85 650 115]);
add_block("simulink/Sinks/To Workspace", model + "/Brake Out", ...
    "VariableName", "brakeCmd", ...
    "SaveFormat", "Array", ...
    "Position", [560 135 650 165]);
add_block("simulink/Sinks/To Workspace", model + "/Target Speed Out", ...
    "VariableName", "targetSpeedRef_mps", ...
    "SaveFormat", "Array", ...
    "Position", [260 255 380 285]);
add_block("simulink/Sinks/To Workspace", model + "/Road Grade Out", ...
    "VariableName", "roadGrade_deg", ...
    "SaveFormat", "Array", ...
    "Position", [260 305 380 335]);

connect(model, "Target Speed/1", "Driver Controller/1");
connect(model, "Road Grade/1", "Vehicle Plant/3");
connect(model, "Vehicle Plant/1", "Driver Controller/2");
connect(model, "Driver Controller/1", "Vehicle Plant/1");
connect(model, "Driver Controller/2", "Vehicle Plant/2");
connect(model, "Vehicle Plant/1", "Vehicle Speed Out/1");
connect(model, "Vehicle Plant/2", "Vehicle Accel Out/1");
connect(model, "Vehicle Plant/3", "Distance Out/1");
connect(model, "Vehicle Plant/4", "Net Force Out/1");
connect(model, "Driver Controller/1", "Throttle Out/1");
connect(model, "Driver Controller/2", "Brake Out/1");
connect(model, "Target Speed/1", "Target Speed Out/1");
connect(model, "Road Grade/1", "Road Grade Out/1");

save_system(model, modelFile);
close_system(model);
end

function buildDriverController(subsystem)
open_system(subsystem);

delete_line_if_exists(subsystem);
delete_contents(subsystem);

add_block("simulink/Ports & Subsystems/In1", subsystem + "/TargetSpeed", ...
    "Position", [30 48 60 62]);
add_block("simulink/Ports & Subsystems/In1", subsystem + "/ActualSpeed", ...
    "Position", [30 108 60 122]);
add_block("simulink/Math Operations/Sum", subsystem + "/Speed Error", ...
    "Inputs", "+-", ...
    "Position", [95 72 120 108]);
add_block("simulink/Math Operations/Gain", subsystem + "/Kp", ...
    "Gain", "driver.Kp", ...
    "Position", [155 55 225 85]);
add_block("simulink/Continuous/Integrator", subsystem + "/Integrator", ...
    "InitialCondition", "0", ...
    "Position", [160 112 190 142]);
add_block("simulink/Math Operations/Gain", subsystem + "/Ki", ...
    "Gain", "driver.Ki", ...
    "Position", [225 112 295 142]);
add_block("simulink/Math Operations/Sum", subsystem + "/Command Sum", ...
    "Inputs", "++", ...
    "Position", [330 74 355 116]);
add_block("simulink/Discontinuities/Saturation", subsystem + "/Throttle Saturation", ...
    "LowerLimit", "0", ...
    "UpperLimit", "1", ...
    "Position", [395 50 435 80]);
add_block("simulink/Math Operations/Gain", subsystem + "/Negative Command", ...
    "Gain", "-1", ...
    "Position", [392 112 432 142]);
add_block("simulink/Discontinuities/Saturation", subsystem + "/Brake Saturation", ...
    "LowerLimit", "0", ...
    "UpperLimit", "1", ...
    "Position", [465 112 505 142]);
add_block("simulink/Ports & Subsystems/Out1", subsystem + "/ThrottleCmd", ...
    "Position", [550 55 580 69]);
add_block("simulink/Ports & Subsystems/Out1", subsystem + "/BrakeCmd", ...
    "Position", [550 117 580 131]);

connect(subsystem, "TargetSpeed/1", "Speed Error/1");
connect(subsystem, "ActualSpeed/1", "Speed Error/2");
connect(subsystem, "Speed Error/1", "Kp/1");
connect(subsystem, "Speed Error/1", "Integrator/1");
connect(subsystem, "Integrator/1", "Ki/1");
connect(subsystem, "Kp/1", "Command Sum/1");
connect(subsystem, "Ki/1", "Command Sum/2");
connect(subsystem, "Command Sum/1", "Throttle Saturation/1");
connect(subsystem, "Command Sum/1", "Negative Command/1");
connect(subsystem, "Negative Command/1", "Brake Saturation/1");
connect(subsystem, "Throttle Saturation/1", "ThrottleCmd/1");
connect(subsystem, "Brake Saturation/1", "BrakeCmd/1");
end

function buildVehiclePlant(subsystem)
open_system(subsystem);

delete_line_if_exists(subsystem);
delete_contents(subsystem);

add_block("simulink/Ports & Subsystems/In1", subsystem + "/ThrottleCmd", ...
    "Position", [30 48 60 62]);
add_block("simulink/Ports & Subsystems/In1", subsystem + "/BrakeCmd", ...
    "Position", [30 108 60 122]);
add_block("simulink/Ports & Subsystems/In1", subsystem + "/RoadGradeDeg", ...
    "Position", [30 168 60 182]);

add_block("simulink/Math Operations/Gain", subsystem + "/Traction Gain", ...
    "Gain", "params.maxTractiveForce", ...
    "Position", [105 42 175 72]);
add_block("simulink/Math Operations/Gain", subsystem + "/Brake Gain", ...
    "Gain", "params.maxBrakeForce", ...
    "Position", [105 102 175 132]);

add_block("simulink/Continuous/Integrator", subsystem + "/Speed Integrator", ...
    "InitialCondition", "params.initialSpeed", ...
    "LimitOutput", "on", ...
    "LowerSaturationLimit", "0", ...
    "UpperSaturationLimit", "inf", ...
    "Position", [525 80 555 110]);
add_block("simulink/Continuous/Integrator", subsystem + "/Distance Integrator", ...
    "InitialCondition", "params.initialDistance", ...
    "Position", [610 80 640 110]);

add_block("simulink/Math Operations/Math Function", subsystem + "/Speed Squared", ...
    "Operator", "square", ...
    "Position", [250 32 290 68]);
add_block("simulink/Math Operations/Gain", subsystem + "/Aero Gain", ...
    "Gain", "0.5 * params.rhoAir * params.Cd * params.frontalArea", ...
    "Position", [320 32 430 68]);

add_block("simulink/Sources/Constant", subsystem + "/Rolling Resistance", ...
    "Value", "params.mass * params.g * params.Crr", ...
    "Position", [315 112 430 142]);

add_block("simulink/Math Operations/Gain", subsystem + "/Deg to Rad", ...
    "Gain", "pi/180", ...
    "Position", [110 165 175 195]);
add_block("simulink/Math Operations/Trigonometric Function", subsystem + "/sin(grade)", ...
    "Operator", "sin", ...
    "Position", [205 165 245 195]);
add_block("simulink/Math Operations/Gain", subsystem + "/Grade Force Gain", ...
    "Gain", "params.mass * params.g", ...
    "Position", [275 165 385 195]);

add_block("simulink/Math Operations/Sum", subsystem + "/Net Force Sum", ...
    "Inputs", "+----", ...
    "Position", [455 126 485 204]);
add_block("simulink/Math Operations/Gain", subsystem + "/Acceleration Gain", ...
    "Gain", "1/params.mass", ...
    "Position", [515 150 595 180]);

add_block("simulink/Ports & Subsystems/Out1", subsystem + "/VehicleSpeed", ...
    "Position", [705 55 735 69]);
add_block("simulink/Ports & Subsystems/Out1", subsystem + "/VehicleAccel", ...
    "Position", [705 135 735 149]);
add_block("simulink/Ports & Subsystems/Out1", subsystem + "/Distance", ...
    "Position", [705 95 735 109]);
add_block("simulink/Ports & Subsystems/Out1", subsystem + "/NetForce", ...
    "Position", [705 175 735 189]);

connect(subsystem, "ThrottleCmd/1", "Traction Gain/1");
connect(subsystem, "BrakeCmd/1", "Brake Gain/1");
connect(subsystem, "RoadGradeDeg/1", "Deg to Rad/1");
connect(subsystem, "Deg to Rad/1", "sin(grade)/1");
connect(subsystem, "sin(grade)/1", "Grade Force Gain/1");
connect(subsystem, "Speed Integrator/1", "Speed Squared/1");
connect(subsystem, "Speed Squared/1", "Aero Gain/1");
connect(subsystem, "Traction Gain/1", "Net Force Sum/1");
connect(subsystem, "Brake Gain/1", "Net Force Sum/2");
connect(subsystem, "Aero Gain/1", "Net Force Sum/3");
connect(subsystem, "Rolling Resistance/1", "Net Force Sum/4");
connect(subsystem, "Grade Force Gain/1", "Net Force Sum/5");
connect(subsystem, "Net Force Sum/1", "Acceleration Gain/1");
connect(subsystem, "Acceleration Gain/1", "Speed Integrator/1");
connect(subsystem, "Speed Integrator/1", "Distance Integrator/1");
connect(subsystem, "Speed Integrator/1", "VehicleSpeed/1");
connect(subsystem, "Acceleration Gain/1", "VehicleAccel/1");
connect(subsystem, "Distance Integrator/1", "Distance/1");
connect(subsystem, "Net Force Sum/1", "NetForce/1");
end

function connect(systemName, source, destination)
add_line(systemName, source, destination, "autorouting", "on");
end

function delete_contents(systemName)
blocks = find_system(systemName, "SearchDepth", 1, "Type", "Block");
blocks = string(blocks);
blocks = blocks(blocks ~= systemName);

for block = blocks'
    delete_block(block);
end
end

function delete_line_if_exists(systemName)
lines = find_system(systemName, "FindAll", "on", "Type", "line");
for idx = 1:numel(lines)
    delete_line(lines(idx));
end
end
